-- 코드를 입력하세요
SELECT DATE_FORMAT(T.SALES_DATE,'%Y-%m-%d') as 'SALES_DATE', T.PRODUCT_ID, T.USER_ID, T.SALES_AMOUNT
FROM (
    SELECT USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE FROM ONLINE_SALE
    UNION ALL
    SELECT NULL, PRODUCT_ID, SALES_AMOUNT, SALES_DATE FROM OFFLINE_SALE
) T
WHERE T.SALES_DATE >= '2022-03-01' AND T.SALES_DATE <'2022-04-01' 
ORDER BY T.SALES_DATE, T.PRODUCT_ID, T.USER_ID;